#!/bin/sh
# postrm script for arrow-judge

set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	if [ -n "`id -u arrow-judge 2>/dev/null`" ]; then
		userdel arrow-judge
	fi
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
